- name: Destroy openshift terraform plan
  terraform:
    project_path: "{{ role_path }}/files"
    backend_config:
      path: "{{ role_path }}/../../.state/az_ocp_infra/{{ ocp_cluster_name }}/terraform.tfstate"
    force_init: true
    variables:
      az_resource_group_name: "{{ az_resource_group_name }}"
      az_client_id: "{{ az_client_id }}"
      az_subscription_id: "{{ az_subscription_id }}"
      az_tenant_id: "{{ az_tenant_id }}"
      az_location: "{{ az_location }}"
      az_network_name: "{{ az_network_name }}"
      az_subnetwork_name: "{{ az_subnetwork_name }}"
      az_dns_zone_name: "{{ az_dns_zone_name }}"
      az_rhcos_image_id: "{{ az_rhcos_image_id }}"
      ocp_cluster_name: "{{ ocp_cluster_name }}"
      ocp_ignition_dir: "{{ ocp_ignition_dir }}"
      ocp_bootstrap_vm_size: "{{ ocp_bootstrap_vm_size }}"
      ocp_master_vm_size: "{{ ocp_master_vm_size }}"
      ocp_master_replicas: "{{ ocp_master_replicas }}"
      ocp_worker_vm_size: "{{ ocp_worker_vm_size }}"
      ocp_worker_replicas: "{{ ocp_worker_replicas }}"
    state: absent